language: node_js
cache:
  directories:
    - node_modules
services:
  - mongodb
  - xvfb
# A workaround for Chrome failure, see: https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
sudo: required
addons:
  chrome: stable
# See: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_install:
  - export DISPLAY=:99.0
install:
  - npm install
  - npm run webdriver:update
script:
  - npm run pre:test:e2e > /dev/null 2>&1 &
  - npm run lint
  - npm run test:server
  - npm run test:angular-unit
  - npm run test:e2e
